version: 1.3.{build}-{branch}
build:
  verbosity: normal
notifications:
- provider: Webhook
  url: http://stats.zomis.net:8081/hooks/appveyor
  headers:
    X-Duga-Event: duga42
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
