version: 2.0.{build}-{branch}
build:
  verbosity: normal

configuration: Release

init:
  - git config --global core.autocrlf true

notifications:
  - provider: Webhook
    url: http://stats.zomis.net:8081/hooks/appveyor?roomId=14929
    headers:
      X-Duga-Event: duga42
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

install:
  - cinst innosetup
  
after_test:
  - iscc /q "Installer Build Script.iss"
  
artifacts:
  - path: Installers\*.exe

hosts:
  api.nuget.org: 93.184.221.200
