version: 2.1.{build}
branches:
  only:
  - next
  - master
image: Visual Studio 2015
configuration: Release
platform: Any CPU
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- ps: choco install innosetup
build:
  verbosity: minimal
artifacts:
- path: Installers\*.exe
  name: Rubberduck
hosts:
  api.nuget.org: 93.184.221.200
before_deploy:
- ps: 
deploy:
- provider: GitHub
  tag: Rubberduck v$(appveyor_build_version)
  release: Rubberduck v$(appveyor_build_version)
  description: (AppVeyor build)
  auth_token:
    secure: oh0SRnZVt0ABeWqFr7ut5TZkxFJjHmS/DZnJnp2HErQTCmX3O8RASJH3ZiYl11gz
  artifact: Installers\*.exe
  draft: false
  prerelease: true
  on:
    branch: next
notifications:
- provider: Webhook
  url: http://stats.zomis.net/GithubHookSEChatService/hooks/github/payload?roomId=14929
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
